### ISSUE TITLE
Error when running IPV8

### ISSUE THREAD

**Issue by devos50** [qstokkink/py-ipv8#1]
When running IPV8, I encountered a stack trace:

```
CRITICAL:root:Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/crawler/py-ipv8/ipv8/messaging/interfaces/endpoint.py", line 44, in _deliver_later
    listener.on_packet(packet)
  File "/home/crawler/py-ipv8/ipv8/deprecated/community.py", line 237, in on_packet
    self.decode_map[data[22]](source_address, data)
  File "/home/crawler/py-ipv8/ipv8/peerdiscovery/deprecated/discovery.py", line 58, in on_similarity_response
    auth, dist, payload = self._ez_unpack_auth(SimilarityResponsePayload, data)
  File "/home/crawler/py-ipv8/ipv8/deprecated/community.py", line 43, in _ez_unpack_auth
    dist, payload, unknown_data = self.serializer.unpack_to_serializables(format, remainder[23:])
  File "/home/crawler/py-ipv8/ipv8/messaging/serialization.py", line 266, in unpack_to_serializables
    out.append(serializable.from_unpack_list(*unpack_list))
  File "/home/crawler/py-ipv8/ipv8/peerdiscovery/deprecated/discovery_payload.py", line 83, in from_unpack_list
    [(tb_overlap[i:i+20], unpack(">I", tb_overlap[i+20:i+24])) for i in range(0, len(tb_overlap), 24)]]
struct.error: unpack requires a string argument of length 4
```

**Comment by qstokkink** [comment]
This is due to an illegal packet being received, we cannot stop others from sending you illegal packets. I could enhance the error reporting of this thoug.
