### ISSUE TITLE
Another error when running IPV8

### ISSUE THREAD

**Issue by devos50** [qstokkink/py-ipv8#2]
```
CRITICAL:root:Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/crawler/py-ipv8/ipv8/messaging/interfaces/endpoint.py", line 44, in _deliver_later
    listener.on_packet(packet)
  File "/home/crawler/py-ipv8/ipv8/deprecated/community.py", line 237, in on_packet
    self.decode_map[data[22]](source_address, data)
  File "/home/crawler/py-ipv8/ipv8/peerdiscovery/deprecated/discovery.py", line 48, in on_introduction_response
    packet = self.create_similarity_request()
  File "/home/crawler/py-ipv8/ipv8/peerdiscovery/deprecated/discovery.py", line 81, in create_similarity_request
    return self._ez_pack(self._prefix, 1, [auth, dist, payload])
  File "/home/crawler/py-ipv8/ipv8/deprecated/community.py", line 25, in _ez_pack
    packet += self.serializer.pack_multiple(format_list)
  File "/home/crawler/py-ipv8/ipv8/messaging/serialization.py", line 182, in pack_multiple
    out += self.pack(*packable)
  File "/home/crawler/py-ipv8/ipv8/messaging/serialization.py", line 170, in pack
    return self._packers[format].pack(*data)
struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by qstokkink** [comment]
Fixed in cdb74384141b332a8d12b2d7c7b4f7c1ffbb5d37.
