### ISSUE TITLE
Windows tests failing completely

### ISSUE THREAD

**Issue by qstokkink** [qstokkink/py-ipv8#23]
```python
Traceback (most recent call last):
File "c:\python27\lib\site.py", line 62, in
import os   
File "c:\python27\lib\os.py", line 400, in
import UserDict   
File "c:\python27\lib\UserDict.py", line 116, in
import _abcoll   
File "c:\python27\lib\_abcoll.py", line 11, in
from abc import ABCMeta, abstractmethod
File "C:\Users\heteoma\Documents\tribler\abc.py", line 15, in
import wx   
ImportError: No module named wx
```

This is a problem with the build machine import path.

**Comment by qstokkink** [comment]
Builder has been fixed.
