### ISSUE TITLE
AssertionError when running IPV8

### ISSUE THREAD

**Issue by devos50** [qstokkink/py-ipv8#3]
When running IPV8, I got the following error:

```
CRITICAL:root:Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/crawler/py-ipv8/ipv8/messaging/interfaces/endpoint.py", line 44, in _deliver_later
    listener.on_packet(packet)
  File "/home/crawler/py-ipv8/ipv8/deprecated/community.py", line 237, in on_packet
    self.decode_map[data[22]](source_address, data)
  File "/home/crawler/py-ipv8/ipv8/peerdiscovery/deprecated/discovery.py", line 58, in on_similarity_response
    auth, dist, payload = self._ez_unpack_auth(SimilarityResponsePayload, data)
  File "/home/crawler/py-ipv8/ipv8/deprecated/community.py", line 47, in _ez_unpack_auth
    unknown_data.encode('HEX'))
exceptions.AssertionError: Incoming packet SimilarityResponsePayload (00027e313685c1912a141279f8248fc8db5899c5df5a020080307e301006072a8648ce3d020106052b81040024036a000400be6c4d4db7412784e0a72d6dad5c5b31d749f54f14fb7e6b748de5cf12f98b3377bc4a839bd73adb4fbf6e12df4dc84ae4613400d3d482bb422372ab8e3b63e5da0fd55aa9404e9aa9c4fa05d94fa2e6e2d1da75540d6645b38f502c9e9ccdb58e083472c3d81d0000000000000002663300017e313685c1912a141279f8248fc8db5899c5df5ac8e701e581942330a0d347eedcdb5048d5d1993e00000001fb23d2f92f3d2256f9af7bd216320eab1c7168bd00000001918552282c7ad9ce5442955540ef406562e72fca000000010a4aca64c779298ed5e26e4e71a859c90191888d00000001d62590448b6c013ebe1a30be18eb5837c06853f8000000012ef3a1ba8f3515ea13881360db451c7e78d8a689000000010e826d8689a9f6d7e20dd16ecfab651d56325149000000014283cc07c7e8262d1541e452b7e13f131caa065b000000012af6ed98b4f5b9446280c2a213fd38922caca05a00000001f694aa4578151549f206969504bae7f54494e6fc00000001c1ce314c76d2a55ccd4fc64bfeb144c777723f1a00000001d0fe3254a87e5f07926bfae86fa8b5207e8c6249000000011761b004430b51fa2508219cbcd67f5bca62f91500000001617975ffab60ce91a34e009f78eab62b03fad0af00000001fab3bc767235090226159744bdd7e43f060f14b800000001cf5fcb34d7b19cb57f4ca5410f35dbb55e2178b1000000014a356204ab68793194a09d5cd6c3d13f468ed1af0000000109e159243c76d7b868635a7b9d70f904ad38ebf900000001d7d6e11e03da72eb6efe5f40498917c755a6927100000001c5205c5e69cd33bd56549060e52a485a7a01647b0000000166ee5b7cb7686352b75f8e273dc1fb50f14e1c8300000001dd60f8406bf991211949d22d0becd006a968d6d50000000174abfb28a2de6f0827a91459b6d84a15a62e837c00000001a7632f3058f61996902c54ef1f03202c59f452af000000015fba30c1475c67aa5a02ac29098a9e3de1c60ef500000001001997f27903eb87cb78f3c23aa6684a5b73aeb04724cc8091f69f46a4de47e06eaffafa1cdad378cc345dca617e6e7fc86ea0210008b27c92be9764f9aef53950e23c6e064a04007b5ec5eba83aeb600eb1b419e091ad03227aca67c585b7699c848fff9183b924) has extra data: (fb23d2f92f3d2256f9af7bd216320eab1c7168bd00000001918552282c7ad9ce5442955540ef406562e72fca000000010a4aca64c779298ed5e26e4e71a859c90191888d00000001d62590448b6c013ebe1a30be18eb5837c06853f8000000012ef3a1ba8f3515ea13881360db451c7e78d8a689000000010e826d8689a9f6d7e20dd16ecfab651d56325149000000014283cc07c7e8262d1541e452b7e13f131caa065b000000012af6ed98b4f5b9446280c2a213fd38922caca05a00000001f694aa4578151549f206969504bae7f54494e6fc00000001c1ce314c76d2a55ccd4fc64bfeb144c777723f1a00000001d0fe3254a87e5f07926bfae86fa8b5207e8c6249000000011761b004430b51fa2508219cbcd67f5bca62f91500000001617975ffab60ce91a34e009f78eab62b03fad0af00000001fab3bc767235090226159744bdd7e43f060f14b800000001cf5fcb34d7b19cb57f4ca5410f35dbb55e2178b1000000014a356204ab68793194a09d5cd6c3d13f468ed1af0000000109e159243c76d7b868635a7b9d70f904ad38ebf900000001d7d6e11e03da72eb6efe5f40498917c755a6927100000001c5205c5e69cd33bd56549060e52a485a7a01647b0000000166ee5b7cb7686352b75f8e273dc1fb50f14e1c8300000001dd60f8406bf991211949d22d0becd006a968d6d50000000174abfb28a2de6f0827a91459b6d84a15a62e837c00000001a7632f3058f61996902c54ef1f03202c59f452af000000015fba30c1475c67aa5a02ac29098a9e3de1c60ef500000001),
```

**Comment by qstokkink** [comment]
Related to #1
